# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
size_of_null_vector = null_vector.nbytes
print(size_of_null_vector)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector1 = np.arange(start=10, stop=50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector2 = np.sort(vector1)[::-1]
print(vector2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1 = np.arange(9)
array2 = array1.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)[0]
print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
np.random.random((3,3,3))

array([[[0.89091499, 0.37932373, 0.42800653],
        [0.1321451 , 0.16911826, 0.18866872],
        [0.84254804, 0.38387864, 0.87414561]],

       [[0.35570477, 0.40291341, 0.75330143],
        [0.23919779, 0.06518802, 0.36682635],
        [0.80159257, 0.39749871, 0.95994823]],

       [[0.58594075, 0.94819873, 0.55570613],
        [0.85146514, 0.34863116, 0.97629997],
        [0.39511691, 0.30647874, 0.32491092]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
matrix12 = np.random.random((10, 10))
print(matrix12)
print('min :', np.min(matrix12), 'max:',np.max(matrix12))

[[0.60414911 0.84549891 0.11728126 0.40043886 0.32810457 0.5974017
  0.62356565 0.22044494 0.20270843 0.45900397]
 [0.38209415 0.7466792  0.49614886 0.90873598 0.36049463 0.87351545
  0.5519612  0.26028354 0.13253491 0.02655668]
 [0.27190949 0.22084094 0.91747462 0.4245126  0.38169768 0.29653713
  0.78225357 0.4851119  0.56297869 0.67686689]
 [0.65302942 0.29438546 0.50082568 0.20346831 0.69651586 0.05310696
  0.15866627 0.87212848 0.28784943 0.12752071]
 [0.16158745 0.68171377 0.02121719 0.54809184 0.90592164 0.26269426
  0.03710646 0.60885079 0.96261052 0.70047308]
 [0.27351578 0.62992687 0.50543325 0.68535088 0.0922463  0.63778901
  0.89915265 0.69104527 0.1005554  0.18150575]
 [0.09717661 0.73662028 0.26804559 0.33742377 0.90060773 0.44052914
  0.73621012 0.53858602 0.11368944 0.72217861]
 [0.10478491 0.03981124 0.32406855 0.30993674 0.22052518 0.9186812
  0.26014465 0.74809072 0.89376577 0.56259278]
 [0.32145487 0.84089108 0.20219437 0.17909226 0.70421466 0.45339427
  0.83238101 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
vector3 = np.random.random(30)
print(vector3)
print('mean:',np.mean(vector3))

[0.93438369 0.69615796 0.53400838 0.35883104 0.69035262 0.27749069
 0.69177517 0.91380229 0.63179234 0.65262311 0.8603976  0.68019163
 0.10983538 0.57475055 0.75265652 0.25807413 0.46258    0.40390122
 0.41841866 0.55212429 0.0928021  0.61095209 0.79419056 0.72471023
 0.38845424 0.6246778  0.69892843 0.90738674 0.43881208 0.37954173]
mean: 0.5704867758242246


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [130]:
Z = np.random.randint(1,10,(5,5))
print(Z)
print(Z[0,1:0])


[[9 1 2 9 7]
 [1 1 2 3 8]
 [8 5 5 1 2]
 [1 9 6 7 3]
 [6 5 4 1 7]]
[]


In [ ]:
matrix14 = np.ones((4,4))
matrix14[1:-1, 1:-1] = 0
print(matrix14)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix16 = np.zeros((5,5))
matrix16[1, 0] = 1
matrix16[2, 1] = 2
matrix16[3, 2] = 3
matrix16[4, 3] = 4
print(matrix16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix17 = np.zeros((8,8))
matrix17[1::2, ::2] = 1
matrix17[::2, 1::2] = 1
print(matrix17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100, shape=(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
matrix19 = np.random.random((5,5))
x_bar = np.mean(matrix19)
std = np.std(matrix19)
matrix19 = (matrix19 - x_bar) / std
print(matrix19)

[[-1.67315061  0.83386135 -0.67561105 -0.231909    0.77193878]
 [ 1.62082186  0.85474316 -1.6906904  -0.3345186  -0.85909318]
 [-1.96226585 -0.30595124  0.07074015 -0.28096532  0.03946395]
 [-0.95401734 -0.42077567 -0.277065    0.6624006  -0.62791557]
 [ 1.70273909  0.43242006  0.6393218   0.97284198  1.69263606]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
RGBA_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(RGBA_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

In [ ]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print(np.dot(A,B))

[[0.73764679 0.74120481]
 [0.68565733 0.90419081]
 [0.46811359 0.54484775]
 [0.39931851 0.43811694]
 [0.66158732 0.7854476 ]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = [1,4,5,7,9]
a = np.array(a)
a[(a>=3) & (a<= 8)] *= -1
print(a)

[ 1 -4 -5 -7  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=1

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

<class 'int'>
1
1
False
1j
1.0
False


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-16-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-16-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-16-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common_values = np.intersect1d(Z1, Z2)
print(common_values)

[2 3 4 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


<ipython-input-22-3364ffefb0a7>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
<ipython-input-22-3364ffefb0a7>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [71]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)

np.add(A, B, out=B)
np.divide(np.negative(A), 2, out=A)
np.multiply(A, B, out=A)

array([ -2.5,  -7. , -13.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
array = np.random.uniform(0,10,10)
print(array)
print(array - array%1)
print(array // 1)

[1.16649918 9.15536599 4.90473471 3.74449742 9.40320288 2.91929909
 7.30310124 9.27363005 0.84664861 5.80435068]
[1. 9. 4. 3. 9. 2. 7. 9. 0. 5.]
[1. 9. 4. 3. 9. 2. 7. 9. 0. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [92]:
matrix = np.random.random((5,5))
print(matrix*4)
# 난수는 항상 0.0 이상 1.0 미만임을 알게 됐다.

[[1.00930298 2.97530342 0.78171792 2.32543571 3.88007996]
 [3.38731521 0.95939104 1.97507886 2.47982287 3.3159236 ]
 [0.62716558 0.07430481 0.28008857 1.94538044 2.42531785]
 [2.27540575 1.26944964 3.95446462 2.31898088 1.52056469]
 [2.20379288 2.98133772 2.67693157 1.05967823 0.26533934]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
z = np.random.random(10)
np.sort(z)

array([0.04982119, 0.22131533, 0.39318655, 0.46625384, 0.48264192,
       0.48385783, 0.50921976, 0.82934151, 0.8843276 , 0.88948324])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
# Set the seed for reproducibility
np.random.seed(1)

# Generate a random 10x2 matrix of Cartesian coordinates
Z = np.random.rand(10, 2)

# Extract X and Y coordinates
X, Y = Z[:, 0], Z[:, 1]

# Compute the radius (r)
R = np.sqrt(X**2 + Y**2)

# Compute the angle (θ) in radians
T = np.arctan2(Y, X)


print("Radius (R):", R)
print("Angle (T):", T)

Radius (R): [0.8323309  0.30233259 0.17338889 0.3925622  0.66913967 0.80327443
 0.90160466 0.67102665 0.69733609 0.24280176]
Angle (T): [1.04600884 1.57041802 0.56161281 1.07643094 0.93607685 1.02176969
 1.34204161 1.52997052 0.92925992 0.95428076]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
x = np.random.random(10)
print(x)

x[x.argmax()] = 0
print(x)

[0.98886109 0.74816565 0.28044399 0.78927933 0.10322601 0.44789353
 0.9085955  0.29361415 0.28777534 0.13002857]
[0.         0.74816565 0.28044399 0.78927933 0.10322601 0.44789353
 0.9085955  0.29361415 0.28777534 0.13002857]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [93]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z); print(v)

differences = np.abs(Z - v)
closest_index = differences.argmin()
closest_value = Z[closest_index]
print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
37.00841979141063
37


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [94]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4
Index: (1, 2), Value: 5
Index: (2, 0), Value: 6
Index: (2, 1), Value: 7
Index: (2, 2), Value: 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [98]:
n = 5
p = 10
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),3)
print(Z)

[[3. 0. 0. 3. 3.]
 [0. 0. 0. 3. 3.]
 [0. 0. 0. 0. 3.]
 [3. 0. 3. 0. 3.]
 [0. 3. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [112]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[:,0] = np.sort(Z[:,0],axis=0)
print(Z)

[[9 4 4]
 [8 2 1]
 [6 3 8]]
[[6 4 4]
 [8 2 1]
 [9 3 8]]


In [114]:
# column 2
Z[:,0:2] = np.sort(Z[:,0:2],axis=0)
print(Z)

[[6 2 4]
 [8 3 1]
 [9 4 8]]


In [115]:
# column 3
Z[:,0:3] = np.sort(Z[:,0:3],axis=0)
print(Z)

[[6 2 1]
 [8 3 4]
 [9 4 8]]
