# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array1 = np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array1 = np.arange(5)
memory_size = array1.nbytes
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 40 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array1 = np.zeros(10)
array1[4] = 1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array1 = np.arange(start=10, stop=50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array1 = np.arange(10)
reversed = array1[::-1]
print(reversed)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
index = np.array([1,2,0,0,4,0])
indices = np.where(index!=0)
print(indices)

[0, 1, 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array = np.random.random((3,3,3))
print(array)

[[[0.84199404 0.74373455 0.0496679 ]
  [0.00165766 0.25379496 0.20689171]
  [0.47360206 0.98607813 0.33650017]]

 [[0.24826759 0.03314916 0.28818301]
  [0.76784268 0.27874308 0.47724397]
  [0.24545102 0.07716977 0.84095696]]

 [[0.34173501 0.43972453 0.79822616]
  [0.03002397 0.71543377 0.76455146]
  [0.41700171 0.32239508 0.24626354]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array1 = np.random.random((10,10))
print(array1)
array1 = np.random.random((10,10))
print('min value:',np.min(array1))
print('max value:',np.max(array1))

[[2.28965109e-01 7.90685742e-01 4.08751868e-02 7.34084642e-01
  2.12514195e-01 6.29966823e-01 4.18260120e-01 4.07612520e-01
  4.32149047e-01 3.05104352e-01]
 [8.74527261e-01 7.96266650e-01 1.25941261e-01 3.60833471e-02
  2.94083619e-01 8.05119715e-01 3.00673269e-01 7.50896020e-01
  2.22017994e-01 5.11791024e-01]
 [7.66386252e-01 8.30723322e-01 7.75071336e-01 8.37642694e-01
  2.05036914e-01 1.43588081e-03 1.51546994e-01 9.66380190e-01
  5.93652995e-01 6.91087718e-02]
 [5.66236555e-01 5.46502597e-01 8.76989704e-01 1.88257484e-01
  1.57243612e-01 5.08442964e-01 8.20275535e-01 7.46005833e-01
  4.88055818e-01 1.65555122e-02]
 [2.85840243e-01 9.97330995e-05 4.78998915e-01 9.19883949e-01
  2.39136586e-01 6.61985145e-01 8.48849919e-01 4.95995301e-01
  4.35046511e-01 7.07789366e-01]
 [9.42758377e-01 3.98758548e-01 8.95206919e-01 8.87659945e-01
  4.43506632e-01 7.76869198e-01 4.92330268e-01 3.38411841e-01
  4.64549216e-01 6.39343820e-01]
 [4.81056141e-01 3.70825920e-01 4.65723411e-02 2.22151232e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array1 = np.random.random(30)
print('mean value of array1:',np.mean(array1))

mean value of array1: 0.48940974186052966


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array1 = np.ones((4,4))
array1[1:-1,1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

-nan
-False
-False
-nan
-False
-False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array1 = np.zeros((5,5))
array1[1,0]=1
array1[2,1]=2
array1[3,2]=3
array1[4,3]=4
print(array1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array1 = np.zeros((8,8))
array1[::2,::2]=1
array1[1::2,1::2]=1
print(array1)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100, shape=(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array1 = np.random.random((5,5))
xbar = array1.mean()
std = array1.std()
normalize_array1 = array1-xbar/std
print(normalize_array1)

[[-1.50827781 -1.78628141 -1.83408428 -2.02539077 -1.57571463]
 [-1.80578416 -1.87147856 -1.68227139 -2.29539336 -2.17153638]
 [-1.72420908 -1.73177773 -2.05956124 -2.09636863 -1.5825456 ]
 [-1.71957114 -1.74452695 -1.91319732 -1.871241   -1.37685535]
 [-1.91823369 -2.05228928 -2.0688847  -1.45571783 -1.66500862]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
rgba_dtype = np.dtype([('red', np.ubyte), ('green', np.ubyte), ('blue', np.ubyte), ('alpha', np.ubyte)])
print(rgba_dtype)

[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3