# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch

import torch


# Create random tensor
tensor_a = torch.rand(7, 7)

print(tensor_a)

tensor([[0.5745, 0.4436, 0.5187, 0.1769, 0.7671, 0.9321, 0.4108],
        [0.9593, 0.9174, 0.7893, 0.2528, 0.6268, 0.7935, 0.7508],
        [0.3717, 0.7147, 0.9374, 0.6799, 0.3840, 0.0296, 0.4940],
        [0.8624, 0.0318, 0.6980, 0.3292, 0.6715, 0.2653, 0.9697],
        [0.6905, 0.0465, 0.0036, 0.6698, 0.2811, 0.6775, 0.9172],
        [0.3204, 0.8025, 0.5617, 0.2572, 0.1582, 0.5140, 0.5837],
        [0.1753, 0.5593, 0.4759, 0.9215, 0.3906, 0.5164, 0.3436]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_b = torch.rand(1, 7)
# Perform matrix multiplication
tensor_b_transposed = tensor_b.T
matrix_product = torch.matmul(tensor_a, tensor_b_transposed)
print(matrix_product)

tensor([[1.8894],
        [2.3751],
        [1.6883],
        [1.9730],
        [1.9295],
        [1.2621],
        [1.8136]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7, 7)
tensor_b = torch.rand(1, 7)

# Matrix multiply tensors
matrix_product = torch.matmul(tensor_a, tensor_b.T)
print(matrix_product)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    # Set the manual seed for the current CUDA device to 1234
    torch.cuda.manual_seed(1234)
    print("CUDA manual seed set to 1234 on the current device.")
else:
    print("CUDA is not available. Using torch.manual_seed on CPU.")
    torch.manual_seed(1234)

CUDA manual seed set to 1234 on the current device.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    print("Device: cuda")
else:
    print("CUDA is not available. Using CPU.")

# Create two random tensors on GPU
tensor_a_gpu = torch.rand(2,3, device='cuda')
tensor_b_gpu = torch.rand(2,3, device='cuda')
print(tensor_a_gpu)
print(tensor_b_gpu)

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
matmul_result = torch.matmul(tensor_a_gpu, tensor_b_gpu.T)
print(matmul_result)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(torch.max(matmul_result))

# Find min
print(torch.min(matmul_result))

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(torch.argmax(matmul_result))

# Find arg min
print(torch.argmin(matmul_result))

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_with_ones = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_without_ones = torch.squeeze(tensor_with_ones)

# Print out tensors and their shapes
print("First Tensor:\n", tensor_with_ones)
print("Shape of First Tensor:", tensor_with_ones.shape)
print("\nSecond Tensor:\n", tensor_without_ones)
print("Shape of Second Tensor:", tensor_without_ones.shape)

First Tensor:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of First Tensor: torch.Size([1, 1, 1, 10])

Second Tensor:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of Second Tensor: torch.Size([10])
